//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sliding_Project_v0._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Material
    {
        public int Distributor_ID { get; set; }
        public string Material_Name { get; set; }
        public int DM_ID { get; set; }
    
        public virtual Distributor Distributor { get; set; }
    }
}
