//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sliding_Project_v0._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Transaction
    {
        public int Transaction_ID { get; set; }
        public int Order_ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Paid { get; set; }
        public int User_ID { get; set; }
        public int Distributor_ID { get; set; }
    
        public virtual Stock_Order Stock_Order { get; set; }
        public virtual Distributor Distributor { get; set; }
        public virtual User User { get; set; }
    }
}
