//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sliding_Project_v0._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Salary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Salary()
        {
            this.Employee_Transaction = new HashSet<Employee_Transaction>();
        }
    
        public int Employee_ID { get; set; }
        public string Post { get; set; }
        public decimal Salary { get; set; }
        public decimal Pending_Salary { get; set; }
        public System.DateTime Last_Paid { get; set; }
    
        public virtual Employee_Details Employee_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Transaction> Employee_Transaction { get; set; }
    }
}
