//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sliding_Project_v0._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_Items
    {
        public int Order_ID { get; set; }
        public string Catagory { get; set; }
        public string Material_Type { get; set; }
        public string Colour { get; set; }
        public string Glass_Type { get; set; }
        public Nullable<int> Track { get; set; }
        public double Height { get; set; }
        public double Width { get; set; }
        public int Quantity { get; set; }
        public string Product_Name { get; set; }
        public int ID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
